### ISSUE TITLE
play-client - sbt compile - cannot find symbol

### ISSUE THREAD

**Issue by dorzey** [vmencik/soap-async#1]
I clone dyour project and ran sbt compile, but I got the following compilation errors:

```
sbt compile
[info] Loading project definition from /home/vagrant/code/soap-async/play-client/project
[info] Set current project to soap-async (in build file:/home/vagrant/code/soap-async/play-client/)
[info] Compiling 3 Scala sources and 7 Java sources to /home/vagrant/code/soap-async/play-client/target/scala-2.10/classes...
[error] /home/vagrant/code/soap-async/play-client/app/async/client/AddNumbersService.java:46: cannot find symbol
[error] symbol  : constructor Service(java.net.URL,javax.xml.namespace.QName,javax.xml.ws.WebServiceFeature[])
[error] location: class javax.xml.ws.Service
[error]         super(__getWsdlLocation(), ADDNUMBERSSERVICE_QNAME, features);
[error]         ^
[error] /home/vagrant/code/soap-async/play-client/app/async/client/AddNumbersService.java:54: cannot find symbol
[error] symbol  : constructor Service(java.net.URL,javax.xml.namespace.QName,javax.xml.ws.WebServiceFeature[])
[error] location: class javax.xml.ws.Service
[error]         super(wsdlLocation, ADDNUMBERSSERVICE_QNAME, features);
[error]         ^
[error] /home/vagrant/code/soap-async/play-client/app/async/client/AddNumbersService.java:62: cannot find symbol
[error] symbol  : constructor Service(java.net.URL,javax.xml.namespace.QName,javax.xml.ws.WebServiceFeature[])
[error] location: class javax.xml.ws.Service
[error]         super(wsdlLocation, serviceName, features);
[error]         ^
[error] 3 errors
[error] (compile:compile) javac returned nonzero exit code
[error] Total time: 9 s, completed Jan 23, 2014 8:56:54 AM
```

I assume the playframework classpath is missing the required jax-ws libraries; but I'm unsure how to add them?

Thanks.

**Comment by vmencik** [comment]
JAX-WS is included in JDK. But unfortunately different versions of Java have different versions of JAX-WS.
The service was generated using JAX-WS 2.2 (https://github.com/vmencik/soap-async/blob/master/play-client/app/async/client/AddNumbersService.java#L16).
What Java version are you using? Any 1.7 release should be fine but you could get this problems with 1.6.

More specifically, you need a JDK that contains JAX-WS >= 2.2 or you have to override the JAX-WS version using the endorsed mechanism. See http://www.bitspedia.com/2012/03/how-to-use-jax-ws-226-with-jdk-16.html

**Comment by dorzey** [comment]
Thanks for the help. It made me check my config; turned out I had mixed up my java versions.

The client now compiles and runs fine. However, when I start the `sbt run` the server I get the following error:

```
[info] Loading project definition from /home/vagrant/code/soap-async/ws-server/project
[info] Set current project to ws-server (in build file:/home/vagrant/code/soap-async/ws-server/)
[info] Running cz.mencik.ws.server.AddNumbersImpl 
[error] (run-main-0) java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at javax.xml.soap.FactoryFinder.newInstance(FactoryFinder.java:47)
    at javax.xml.soap.FactoryFinder.find(FactoryFinder.java:193)
    at javax.xml.soap.FactoryFinder.find(FactoryFinder.java:97)
    at javax.xml.soap.SAAJMetaFactory.getInstance(SAAJMetaFactory.java:73)
    at javax.xml.soap.MessageFactory.newInstance(MessageFactory.java:145)
    at com.sun.xml.internal.ws.api.SOAPVersion.<init>(SOAPVersion.java:165)
    at com.sun.xml.internal.ws.api.SOAPVersion.<clinit>(SOAPVersion.java:71)
    at com.sun.xml.internal.ws.api.BindingID.<clinit>(BindingID.java:324)
    at com.sun.xml.internal.ws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:110)
    at javax.xml.ws.Endpoint.publish(Endpoint.java:240)
    at cz.mencik.ws.server.AddNumbersImpl.main(AddNumbersImpl.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
Caused by: java.util.MissingResourceException: Can't find com.sun.xml.internal.messaging.saaj.soap.LocalStrings bundle
    at java.util.logging.Logger.setupResourceInfo(Logger.java:1518)
    at java.util.logging.Logger.<init>(Logger.java:265)
    at java.util.logging.Logger.<init>(Logger.java:260)
    at java.util.logging.LogManager$SystemLoggerContext.demandLogger(LogManager.java:763)
    at java.util.logging.LogManager.demandSystemLogger(LogManager.java:454)
    at java.util.logging.Logger.demandLogger(Logger.java:340)
    at java.util.logging.Logger.getLogger(Logger.java:439)
    at com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl.<clinit>(SAAJMetaFactoryImpl.java:41)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at javax.xml.soap.FactoryFinder.newInstance(FactoryFinder.java:47)
    at javax.xml.soap.FactoryFinder.find(FactoryFinder.java:193)
    at javax.xml.soap.FactoryFinder.find(FactoryFinder.java:97)
    at javax.xml.soap.SAAJMetaFactory.getInstance(SAAJMetaFactory.java:73)
    at javax.xml.soap.MessageFactory.newInstance(MessageFactory.java:145)
    at com.sun.xml.internal.ws.api.SOAPVersion.<init>(SOAPVersion.java:165)
    at com.sun.xml.internal.ws.api.SOAPVersion.<clinit>(SOAPVersion.java:71)
    at com.sun.xml.internal.ws.api.BindingID.<clinit>(BindingID.java:324)
    at com.sun.xml.internal.ws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:110)
    at javax.xml.ws.Endpoint.publish(Endpoint.java:240)
    at cz.mencik.ws.server.AddNumbersImpl.main(AddNumbersImpl.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 1 s, completed Jan 24, 2014 9:35:52 AM
```

I've already confirmed that my `JAVA_HOME` is pointing to the correct place. I am using OpenJDK 1.7.0_51.

**Comment by city81** [comment]
jdk7u25 removed the stack search for a resource bundle for Logger to use so the workaround is to set a system property. Could do:

sbt -Djdk.logging.allowStackWalkSearch=true run

or edit the build.sbt file to include:

fork in run := true

javaOptions in (run) += "-Djdk.logging.allowStackWalkSearch=true"

**Comment by carolinux** [comment]
@city81 Your suggestion worked for me! I don't really understand what's going on though.

**Comment by arobertn** [comment]
I faced this issue also, using Java 1.8, sbt 0.13.7.  In addition to the fix mentioned, I needed `connectInput in run := true` also in the `build.sbt`, as per https://github.com/sbt/sbt/issues/229.

May I request that this config get added to the project by default?  I'm not sure how often 1.7 < 25 is being used now.

**Comment by vmencik** [comment]
I've updated the project with the fixes above. BTW with Java >= 8u40 they [should not be necessary](http://bugs.java.com/view_bug.do?bug_id=8066077).
I've also updated the Play project to Play 2.4.6 and Scala 2.11.7.

**Comment by arobertn** [comment]
Not sure if the cited JDK fix ever made it out of a beta build to the mainline or if the bug just recurred later, but I experienced it under 1.8.0_72.  Anyway, good that the workaround is in this project now.
